### ISSUE TITLE
Mayo CTS2 Maven repo unavailable - edu.informatics.maven.release

### ISSUE THREAD

**Issue by XcrigX** [lexevs/lexevs#100]
At this link, under "Getting the Framework"
https://wiki.nci.nih.gov/display/LexEVS/LexEVS+6.x+CTS2+API+Quick+Start

It references this maven repository:
`
<repository>
      <id>edu.informatics.maven.release</id>
      <name>Informatics Maven Release Repository</name>
      <url>http://informatics.mayo.edu/maven/content/repositories/releases</url>
</repository>
`
This repo appears to be unavailable for at least the last few days I've been trying to reach it.  Does anyone know who to contact, or an alternate location to find the CTS2 core framework Java library? 
`
<dependency>
      <groupId>edu.mayo.cts2.framework</groupId>
      <artifactId>core</artifactId>
      <version>0.8.0</version>
</dependency>
`

**Comment by hsbauer** [comment]
We recently updated our repository.  Apologies for this oversight.  The new repo URL should be https://ncimvn.nci.nih.gov/nexus/content/repositories/LexEVSRelease.  The latest stable framework release should be 1.2.1.FINAL, but 0.8.0 is still out there if that's where you are at.

**Comment by XcrigX** [comment]
Excellent, thank you. I see you updated the confluence page. Please note, I believe you need to update the dependency artifactID from "core" to "cts2-core" to reach the 1.2.1.FINAL version.
