### ISSUE TITLE
Can't access imported terminology

### ISSUE THREAD

**Issue by raphaeloneves** [lexevs/lexevs#150]
Hi guys!
I made a subset and have imported ICD10 from Metathesaurus. The codescheme is being listed into CTS2 Service, but when I click into the link (http://myserver/cts2/codesystem/ICD-10/version/2010 to view the detailed information about ICD10, CTS2 service returns me the following error:

```
<UnknownCodeSystemVersion xmlns="http://www.omg.org/spec/CTS2/1.1/Exceptions" xmlns:core="http://www.omg.org/spec/CTS2/1.1/Core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/CTS2/1.1/Exceptions http://informatics.mayo.edu/cts2/spec/CTS2/1.1/core/Exceptions.xsd">
<message>
<core:value>Resource with Identifier: Name: '2010' not found.</core:value>
</message>
<severity>ERROR</severity>
</UnknownCodeSystemVersion>
```

I also tried to import ICD 10 with OWL file. Same problem. Can you help me, please?

PS: i have SNOMEDCT imported and running without problem in the same LexEVS instance.

Regards,

Raphael

**Comment by hsbauer** [comment]
Hello Raphael:
What is the result of calling http://myserver/cts2/codesystemversions?

**Comment by raphaeloneves** [comment]
Hi @hsbauer, when i access codesystemversions resource, all my codeschemes are listed, including ICD10. But when I expand ICP10 codescheme and click in the href option, the error is shown. If i do the same process with SNOMED CT, it works normally.

**Comment by hsbauer** [comment]
Ok, that narrows our issue somewhat. So long as the base url for SNOMED and ICD10 are the same we should be ok.  I'd suggest we look at the container logs next.  Does the output to catalina.out contain any LexEVS related errors that correlate to the href resolution?

**Comment by raphaeloneves** [comment]
@hsbauer, my catalina.out has no errors, so i resolved to restart the container, and guess what?! It worked.
Tks.
Raphael

**Comment by hsbauer** [comment]
New loads will require a server restart.  So if you load new content, the server will always require a recycle.  Good luck and let us know, if you can, what your use case for CTS2 and LexEVS might be.
