### ISSUE TITLE
LexBIG API queries find no matches

### ISSUE THREAD

**Issue by gmadekunle** [lexevs/lexevs#17]
Hello,
Quoted below is my original issue (that I posted to the NCIP Hub before being directed here):
"Please I need some help here:
I have LexBIG version 2.3.0 installed and I have it loaded with 9 code systems subsetted from the UMLS Metathesaurus:
ICD10CM, ICD10PCS, ICD9CM, LNC248, MTHICD9, NDFRT, NDFRT_FDASPL, NDFRT_FMTSME, and RXNORM.
The system runs on a PostgreSQL server 9.4, Windows Vista 32bit. The problem I am having is that whenever I run a query with the API, no results are returned. There are no exceptions thrown and the LexBIG logs do not indicate any errors. The bundled examples give the same empty result. A simple search for 'Cancer' returns no matches. Similarly a search for 'blood' using the SoundsLike class returns no response as well even though browsing the dataset from the admin gui shows that there are many matching concepts and descriptions in the corpus.
Could anyone please tell me what I might be doing wrong or what might be wrong with the installation. Any hints would be welcome. Thank you."

I was advised to upgrade to version 6.x and also, preferably, to run it with a MySQL 5.x database. I have done both (i.e. installed LexEVS 6.2 with MySQL 5.6) but still no results. Can someone please tell me what else could be wrong? Could I have skipped something? Here are some more details:

a) The above substets are from the 2014AB UMLS Active Release Files
b) I have tested all the example classes both from source and from the bundled batch files. Still no results found.
c) Correction to the quote above: Instead of the "admin gui", I meant "metamorphosis subset browser". 
d) In the Admin GUI, the installed Coding Schemes are listed but none of them displays any data when selected and from the bottom left section and the "Resolve Code Set" button is clicked.
e) The tests in the Test Suite where 100% successful after installation
f) I have activated each coding scheme
g) I have tried each coding scheme untagged and with the tag PRODUCTION

Any suggestion is welcome.

**Comment by hsbauer** [comment]
LexEVS 6.2 needs MySQL 5.5 to run.  Things should work fine once that's installed.  Please send along any logs from your install if you continue to have problems.

**Comment by gmadekunle** [comment]
Thank you hsbauer. I'll let you know if any other issues arise.

**Comment by gmadekunle** [comment]
Thank you hsbauer. The issue has been solved. It turned out that the subset that I loaded into LexEVS was created with versioned source abbreviations instead of a versionless one. When I created a new subset with versionless SAB and loaded it afresh into LexEVS, the queries worked fine. I have moved to MySQL 5.5 as you recommended, however I get the following errors and warning everytime LexEVS runs:

log4j:ERROR Could not find value for key log4j.appender.debug
log4j:ERROR Could not instantiate appender named "debug".
LB_WARN_LOGGER WARN - 2015-03-03 07:43:38,166 - [LOG_ID 10] No user defined Cache Settings available, using defaults.
SLF4J: This version of SLF4J requires log4j version 1.2.12 or later. See also http://www.slf4j.org/codes.html#log4j_version
net.sf.ehcache.config.ConfigurationFactory WARN - 2015-03-03 07:43:51,907 - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/C:/LexEVS/6.0/runtime/lbRuntime.jar!/ehcache-failsafe.xml

Can you please point out how to fix them. It doesn't seem like a big problem since it doesn't disturb my queries but it bothers me each time it shows up. 

Finally, as an aside, is there a way queries can be sped up? The system takes quite a while to return matches to queries from the API.

**Comment by hsbauer** [comment]
You can safely ignore the log4j jar clashes.  Much of what happens in the Lucene based search index of LexEVS, happens in memory so make sure you have at least 4 to 6gb available for LexEVS alone when you start up the VM that it runs on.  Add more if you are using larger terminologies such as the NCI Metathesaurus or even SNOMED.  You will want to be sure you keep the indexes themselves on a local drive.  Putting them on a shared drive slows performance considerably.  If you are reaching your database over a network this also can be a problem.  You might try a local install of MySQL if that is the case.  If you have not read our suggestions in the LexEVS documentation for optimizing MySQL I'd suggest you do so.   https://wiki.nci.nih.gov/display/LexEVS/LexEVS+6.x+Local+Runtime+MySQL+Properties+Guide

**Comment by gmadekunle** [comment]
OK, and thanks for all the help.
