### ISSUE TITLE
Unable to build LexEVS 6.3.0.FINAL - fails with Castor error

### ISSUE THREAD

**Issue by CarthageKing** [lexevs/lexevs#26]
Hello,

I am trying to build LexEVS 6.3.0.FINAL. I run the Ant build from the top directory. Eventually I get to the lbModel subproject then I get the error as attached.
[outbuild.txt](https://github.com/lexevs/lexevs/files/190281/outbuild.txt)

Specifically, I'm getting an error during the call to Castor to generate source files from XSDs (i.e. from line 2187). I checked the builtins.xsd and there's no "html" element in there, so I'm stumped as to what the cause is.

I'm attaching a test project that uses just Castor and some XSDs from the project and I get the same error.

[castor-example.zip](https://github.com/lexevs/lexevs/files/190286/castor-example.zip)

Lastly, I get the same error even if I use "xjc" command.

**Comment by hsbauer** [comment]
You say you are building from the top directory.  LexEVS should be built by running ant from the lbPackager project.  Is this what you are trying to do?

**Comment by CarthageKing** [comment]
Thanks for the quick reply.

There is a build.xml on the top-level directory that contains all the subprojects. I ran ant from there and got the error.

Now I just ran ant from the lbPackage project and still get the same error.

**Comment by hsbauer** [comment]
Not sure my earlier comment focuses on your problem, but I've checked out the v6.3.0.FINAL tag and it builds fine from my environment.  Don't know that I can tie the mangling of the xsd resolution to a firewall but I can reach the posted xsd's so It appears they are properly resolving.  You might update ant versions and make sure you are not introducing any extra XML parsing libraries or different castor libraries to the environment.

**Comment by CarthageKing** [comment]
I tried compiling it on my personal laptop and it was successful.

So there must be something in my corporate laptop that's messing with the xsd resolution. I mean I can download the xsd just fine in Chrome and it even validates on XmlSpy. I'll have it checked out with our IT guys this Monday.

Thanks for the help.

**Comment by hsbauer** [comment]
You are welcome. If you become a user please let us know more details about your use case.

Sent from my iPhone

On Mar 25, 2016, at 10:16 PM, CarthageKing <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried compiling it on my personal laptop and it was successful.

So there must be something in my corporate laptop that's messing with the xsd resolution. I mean I can download the xsd just fine in Chrome and it even validates on XmlSpy. I'll have it checked out with our IT guys this Monday.

Thanks for the help.
